class Strings {
  /// HomePage
  static const String home = "Accueil",
      listeDeclaration = "Déclarations",
      setting = "Paramètres",
      stats = "Statistiques",
      crisisMap = "Crisis MAP",
      incidentReporting = "Signalement d'incident",
      byVideo = "Par vidéo",
      byVideoDescription = "Vous pouvez déclarer un incident par vidéo",
      byAudio = "Par audio",
      byAudioDescription = "Vous pouvez déclarer un incident par audio",
      byWriting = "Par écrit",
      byWritingDescription = "Vous pouvez déclarer un incident par écrit",
      rapport = "Incidents",
      rapportDescription = "Cliquer pour voir la liste des incidents",
      urgence = "Urgences",
      urgneceDescription = "Cliquer pour voir la liste des urgences",
      stats_ = "Statistiques",
      statsDescription = "Cliquer pour voir la liste les statistiques",
      reportEmergency = "Signaler une urgence",
      filterList = "Rechercher...";

  static const List<String> communityList = <String>[
    'Choisissez la prefecture',
    "Préfecture d'Avé",
    "Préfecture du Golfe",
    "Préfecture des Lacs",
    "Préfecture de Vo",
    "Préfecture de Yoto",
    "Préfecture du Zio",
    "Préfecture de Bas-Mono",
    "Préfecture d'Agoè-Nyivé",
    "Préfecture d'Agou",
    "Préfecture d'Akébou",
    "Préfecture d'Amou",
    "Préfecture d'Anié",
    "Préfecture de Danyi",
    "Préfecture d'Est-Mono",
    "Préfecture de Haho",
    "Préfecture du Kloto",
    "Préfecture du Moyen-Mono",
    "Préfecture d'Ogou",
    "Préfecture de Wawa",
    "Préfecture de Kpélé",
    "Préfecture de Blitta",
    "Préfecture de Mô",
    "Préfecture de Sotouboua",
    "Préfecture de Tchamba",
    "Préfecture de Tchaoudjo",
    "Préfecture de Kozah",
    "Préfecture d'Assoli",
    "Préfecture de Bassar",
    "Préfecture de la Binah",
    "Préfecture de la Dankpen",
    "Préfecture de Doufelgou",
    "Préfecture de Kéran",
    "Préfecture de Cinkassé",
    "Préfecture de Kpendjal",
    "Préfecture de Kpendjal-Ouest",
    "Préfecture de l'Oti",
    "Préfecture de l'Oti-Sud",
    "Préfecture de Tandjouaré",
    "Préfecture de Tône",
  ];
  static const List<String> cityList = <String>[
    'Choisir la commune',
    'CINKASSE 1 (CINKASSE)',
    'CINKASSE 2 (TIMBOU)',
    'TONE 1 (DAPAONG)',
    'TONE 2 (NAKI EST)',
    'TONE 3 (TAMI)',
    'TONE 4 (KORBONGOU)',
    'KPENDJAL 1 (MANDOURI)',
    'KPENDJAL 2 (BORGOU)',
    'KPENDJAL OUEST (NAKI EST)',
    'KPENDJAL OUEST 2 (POGNO)',
    'TANDJOUARE 1 (TANDJOUARE)',
    'TANDJOUARE 2 (NANO)',
    'OTI 1 (MANGO)',
    'OTI 2 (BARKOISSI)',
    'OTI SUD 1 (GANDO)',
    'OTI SUD 2 (TAKPAMBA)',
    'ASSOLI 1 (BAFILO)',
    'ASSOLI 2 (ALEDJO)',
    'ASSOLI 3 (SOUDOU)',
    'BASSAR 1 (BASSAR)',
    'BASSAR 2 (BANDJELI)',
    'BASSAR 3 (KABOU)',
    'BINAH 1 (PAGOUDA)',
    'BINAH 2 (KETAO)',
    'KANTE 1 (KANTE)',
    'KANTE 2 (ATALOTE)',
    'KANTE 3 (NADOBA)',
    'KOZAH 1 (KARA)',
    'KOZAH 2 (PYA)',
    'KOZAH 3 (AWANDJELO)',
    'KOZAH 4 (ATCHANGBADE)',
    'DOUFELGOU 1 (NIAMTOUGOU)',
    'DOUFELGOU 2 (DEFALE)',
    'DANKPEN 1 (GUERIN KOUKA)',
    'DANKPEN 2 (NAMON)',
    'DANKPEN 3 (BAPURE)',
    'TCHAOUDJO 1 (SOKODE)',
    'TCHAOUDJO 2 (LAMA-TESSI)',
    'TCHAOUDJO 3 (ALEHERIDE)',
    'TCHAOUDJO 4 (AGOULOU)',
    'SOTOUBOUA 1 (SOTOUBOUA)',
    'SOTOUBOUA 2 (ADJENGRE)',
    'SOTOUBOUA 3 (TCHEBEBE)',
    'MO 1 (DJARPANGA)',
    'MO 2 (TINDJASSI)',
    'TCHAMBA 1 (TCHAMBA)',
    'TCHAMBA 2 (TCHAMBA)',
    'TCHAMBA 3 (KABOLI)',
    'BLITTA 1 (BLITTA GARE)',
    'BLITTA 2 (AGBANDI)',
    'BLITTA 3 (M\'POTI)',
    'OGOU 1 (ATAKPAME)',
    'OGOU 2 (DATCHA)',
    'OGOU 3 (GLEI)',
    'OGOU 4 (OUNTIVOU)',
    'ANIE 1 (ANIE)',
    'ANIE 2 (ADOGBENOU)',
    'EST MONO 1 (ELAVAGNON)',
    'EST MONO 2 (MORETAN)',
    'EST MONO 3 (NYAMASSILA)',
    'KLOTO 1 (KPALIME)',
    'KLOTO 2 (LAVIE)',
    'KLOTO 3 (KOUMA)',
    'KPELE 1 (ADETE)',
    'KLOTO 3 (KPELE ELE)',
    'AGOU 1 (AGOU-TAVIE)',
    'AGOU 2 (AMOUSSOUKOPE)',
    'DANYI 2 (DANYI APEYEME)',
    'DANYI 2 (DANYI- ELAVAGNON)',
    'HAHO 1 (NOTSE)',
    'HAHO 2 (ASRAMA)',
    'HAHO 3 (KPEDOME)',
    'HAHO 4 (WAHALA)',
    'MOYEN MONO 1 (TOHOUN)',
    'MOYEN MONO 2 (KPEKLEME)',
    'AMOU 1 (OUMA-AMLAME)',
    'AMOU 2 (AMOU-OBLO)',
    'AMOU 3 (HIHEATRO)',
    'WAWA 1 (ATAKPAME)',
    'WAWA 2 (GBADI-N’KUGNA)',
    'WAWA 2 Doum (OKOU)',
    'AKEBOU 1 (KOUGNOHOU)',
    'AKEBOU 2 (KAMINA-AKEBOU)',
    'AVE 1 (KEVE)',
    'AVE 2 (NOEPE)',
    'LACS 1 (ANEHO)',
    'LACS 2 (AKLAKOU)',
    'LACS 3 (AGBODRAFO)',
    'LACS 4 (ANFOIN)',
    'BAS MONO 1 (AFAGNAN)',
    'BAS MONO 2 (ATTITOGON)',
    'VO 1 (VOGAN)',
    'VO 2 (TOGOVILLE)',
    'VO 3 (DZREKPO)',
    'VO 4 (AKOUMAPE)',
    'YOTO (TABLIGBO)',
    'ZIO 1 (TSEVIE)',
    'ZIO 2 (AGBELOUVE)',
    'ZIO 3 (GAPE-CENTRE)',
    'ZIO 4 (KOVIE)',
    'AGOE-NYIVE 1 (AGOE-NYIVE)',
    'AGOE-NYIVE 2 (LEGBASSITO)',
    'AGOE-NYIVE 3 (VAKPOSSITO)',
    'AGOE-NYIVE 4 (TOGBLEKOPE)',
    'AGOE-NYIVE 5 (SANGUERA)',
    'AGOE-NYIVE 6 (ADEDITKOPE)',
    'GOLFE 1 (BE)',
    'GOLFE 2 (HEDZRANAWOE)',
    'GOLFE 3 (DOUMASSESSE)',
    'GOLFE 4 (AMOUTIVE)',
    'GOLFE 5 (AFLAO GAKLI)',
    'GOLFE 6 (BAGUIDA)',
    'GOLFE 7 (AFLAO-SAGBADO)',
  ];
  static const List<String> rankList = <String>[
    'Collecteur',
    'Responsable de zone'
  ];
  static const List<String> zoneType = <String>[
    'Zone nationale',
    'Zone préfectorale'
  ];
  static const List<String> prefectur = <String>[
    'Prefecture du Golfe',
    'Zone préfectorale'
  ];
  static const List<String> ageInterval = <String>[
    '18 - 30',
    '31 - 50',
    'Plus de 50'
  ];
}
